# Перечень источников. Включайте/выключайте без изменения кода.
# state: active | manual (ручная проверка) | disabled

- name: НОТИМ
  id: notim
  type: html
  url: https://notim.ru/news/
  state: active

- name: Минстрой России
  id: minstroyrf
  type: html
  url: https://minstroyrf.gov.ru/press/?d=all
  state: manual   # 401 из GitHub Actions

- name: АРД: статьи
  id: ard
  type: html
  url: https://ardexpert.ru/article
  state: active

- name: Гостинформ
  id: gostinfo
  type: html
  url: https://www.gostinfo.ru/News/List
  state: active

- name: ФАУ ФЦС
  id: faufcc
  type: html
  url: https://faufcc.ru/press-tsentr/novosti
  state: active

- name: АНЦБ
  id: ancb
  type: html
  url: http://ancb.ru/publication
  state: manual   # частые таймауты

- name: ЕЭК ЕАЭС
  id: eec
  type: html
  url: https://eec.eaeunion.org/news/
  state: active

- name: Минфин России
  id: minfin
  type: html
  url: https://minfin.gov.ru/ru/press-center/
  state: active

- name: Интерфакс-Недвижимость
  id: interfax_realty
  type: html
  url: https://www.interfax-russia.ru/realty/news
  state: active

- name: Металлоснабжение и сбыт
  id: metalinfo
  type: rss
  url: https://www.metalinfo.ru/ru/news/list.rss
  state: active   # теперь берём только /ru/news/<id>

- name: Парламентская газета: Экономика
  id: pnp
  type: html
  url: https://www.pnp.ru/economics/
  state: active

- name: ЕРЗ.РФ
  id: erzrf
  type: html
  url: https://erzrf.ru/news/
  state: active

- name: РИА Недвижимость: лента
  id: ria_realty
  type: html
  url: https://realty.ria.ru/lenta/
  state: active

- name: Правительство РФ
  id: government
  type: rss
  url: http://government.ru/rss/news/
  state: active

- name: Стройгаз.ру
  id: stroygaz
  type: html
  url: https://stroygaz.ru/news/
  state: active

- name: Главгосэкспертиза
  id: gge
  type: html
  url: https://gge.ru/press-center/news/
  state: manual   # 403 (Cloudflare)
