name: Build feed

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build feed
        run: |
          python -m src.build
      - name: Commit & push updated JSON
        run: |
          git config user.name "news-bot"
          git config user.email "actions@github.com"
          git add docs/unified.json
          git commit -m "Update unified.json [skip ci]" || echo "No changes"
          git push
