name: Build unified feed

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'  # раз в час + 10 минут

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build feed
        run: python -m newsfeed.build
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update unified.json"
          file_pattern: docs/unified.json
