name: Build unified feed

on:
  schedule:
    - cron: '0 */3 * * *'  # каждые 3 часа
  workflow_dispatch:
  push:
    paths:
      - 'sources.json'
      - 'scripts/**'
      - '.github/workflows/build.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore .cache/pages (HTML cache)
        uses: actions/cache@v4
        with:  
          path: .cache/pages
          key: pages-${{ hashFiles('sources.json', 'scripts/aggregate.py') }}-${{ github.run_id }}
          restore-keys: |
            pages-${{ hashFiles('sources.json', 'scripts/aggregate.py') }}-
            pages-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed
        run: |
          python scripts/aggregate.py

      - name: Commit output (docs/unified.json)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/unified.json .cache/state.json || true
          git commit -m "Update unified feed [skip ci]" || echo "No changes"
          git push
